name: "CD Pipeline"

on:
  workflow_run:
    workflows: ["artifact upload"] 
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: "Download build files"
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: List downloaded files
        run: ls -la
