name: download

on:
  workflow_run:
    workflows: ["artifact upload"]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Debug environment variables
        run: printenv
        
      - name: "Download build files"
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ github.event.workflow_run.id }}

      - name: List downloaded files
        run: ls -R
