name: "CD Pipeline"

on:
  workflow_run:
    workflows: ["artifact upload"] 
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: "Setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: "Setup vercel cli"
        run: npm install -g vercel

      - name: "Get artifact ID from workflow run"
        id: get_artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ARTIFACT_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts" \
            | jq -r '.artifacts[] | select(.name=="build") | .id')

          if [ -z "$ARTIFACT_ID" ]; then
            echo "No artifact named 'build' found!"
            exit 1
          fi

          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_OUTPUT

      - name: "Download artifact ZIP"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L -H "Authorization: token $GITHUB_TOKEN" \
            -o build.zip \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ steps.get_artifact.outputs.ARTIFACT_ID }}/zip"

      - name: "Extract artifact"
        run: unzip build.zip

      - name: "Deploy to vercel"
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name=cicdproject
